# Generated by Django 4.2.3 on 2024-02-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_reference_id_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='reference_id',
        ),
        migrations.AddField(
            model_name='referenceid',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userprofile'),
        ),
    ]
