# Generated by Django 4.2.3 on 2024-02-16 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_reference_id_delete_referenceid_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_id',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
