# Generated by Django 4.2.3 on 2024-02-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_reference_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_id',
            name='user',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
