# Generated by Django 4.2.3 on 2024-02-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
