# Generated by Django 4.2.3 on 2024-02-25 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
